matrix:
  include:
    - os: osx
      osx_image: xcode9.3
    - os: linux
      sudo: false
      dist: trusty

language: node_js

node_js:
  - "9"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - CXX=clang++
    - CC=clang

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:snappy-dev/tools'
      - sourceline: 'ppa:marutter/rrutter'
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - libxkbfile-dev
      - libx11-dev:i386
      - libx11-dev
      - libxml2-dev
      - gcc-4.8
      - g++-4.8
      - ninja-build
      - rpm
      - libappindicator1
      - libdbus-1-dev
      - libgtk2.0-dev
      - libnotify-dev
      - libgnome-keyring-dev
      - libgconf2-dev
      - libasound2-dev
      - libcap-dev
      - libcups2-dev
      - libxtst-dev
      - libxss1
      - libxss-dev
      - libnss3-dev
      - libxext-dev
      - snapd
      - graphicsmagick
      - xz-utils
      - libc6-dev-i386
      - gcc-4.8-multilib
      - g++-4.8-multilib
      - linux-libc-dev:i386
      - linux-libc-dev
      - clang-3.3

cache:
  directories:
  - "$HOME/.electron"
  - "$HOME/.cache"

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
      export PATH="/tmp/git-lfs:$PATH"
    fi
  - git clone https://$GH_TOKEN@github.com/ramboxapp/desktop.git
  - cd desktop
  - rm yarn.lock

install:
  - npm install

before_script:
  - git lfs pull

script:
  - npm run build

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: change
