matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - CXX=g++
    - os: linux
      sudo: required
      dist: trusty
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - CXX=g++
        - TRAVIS=travis CXX=g++-4.8

language: node_js

node_js:
- "9"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - g++-multilib
      - libxkbfile-dev
      - libx11-dev:i386
      - libx11-dev
      - gcc-4.8
      - g++-4.8
      - ninja-build

compiler:
  - gcc
  - clang

cache:
  directories:
  - "$HOME/.electron"
  - "$HOME/.cache"

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
      export PATH="/tmp/git-lfs:$PATH"
    fi
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo apt-add-repository -y ppa:snappy-dev/tools;
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo add-apt-repository -y ppa:marutter/rrutter;
      sudo apt-get update -qq;
      sudo apt-get install -qq libxml2-dev;
      sudo apt-get install -qq libappindicator1;
      sudo apt-get install -qq rpm;
      sudo apt-get install -y -qq snappy-tools;
      sudo apt-get install -y -qq snapcraft;
      sudo apt-get install --no-install-recommends -y graphicsmagick xz-utils;
      sudo ldconfig
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libx11-dev libxext-dev libxss-dev libxkbfile-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y build-essential clang libdbus-1-dev libgtk2.0-dev libnotify-dev libgnome-keyring-dev libgconf2-dev libasound2-dev libcap-dev libcups2-dev libxtst-dev libxss1 libnss3-dev gcc-multilib g++-multilib; fi
  - git clone https://$GH_TOKEN@github.com/ramboxapp/desktop.git
  - cd desktop
  - rm yarn.lock

install:
  - npm install

before_script:
  - git lfs pull

script:
  - npm run electron-rebuild
  - travis_wait npm run build

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: change
